### ISSUE TITLE
Missing publish file.

### ISSUE THREAD

**Issue by yuriilychak** [englercj/tsd-jsdoc#50] opened 2018-09-25 09:13 UTC
After install from npm and trying to generate definition, have this problem.
[JSDOC] FATAL: Unable to load template: Cannot find module '.../node_modules/tsd-jsdoc/publish'

**Comment by englercj** [comment] 2018-09-25 20:40
Duplicate of #48

**Closed by englercj** 2018-09-25 20:40 UTC
