### ISSUE TITLE
Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by wimrijnders** [englercj/tsd-jsdoc#34] opened 2017-10-12 06:52 UTC
Hi there, while trying out `tsd-jsdoc` on [`vis.js`](), I got the error mentioned in the title, at [this location](https://github.com/englercj/tsd-jsdoc/blob/master/src/Emitter.ts#L257-L261) in the code:

```js
for (let i = 0; i < o.members.length; ++i) {   // <== Cannot read property 'length' of undefined
  if (o.members[i].kind === 'constructor') {
    ctorObj = o.members[i] as dom.ConstructorDeclaration;
  }
}
```

There is no urgency to have this fixed, just trying it out. But could you supply me with a workaround to continue?

**Comment by joelhegg** [comment] 2017-10-18 18:42
See the same issue with actions-on-google.

**Comment by joelhegg** [comment] 2017-10-26 17:33
In the actions-on-google case the problem was there was a typedef and a class with the same name. I deleted the typedef and the problem went away.

**Comment by englercj** [comment] 2017-10-27 15:06
That sounds like an issue, but the lib still shouldn't crash. Sorry I just haven't had time to look into this lately. I will get back to it at some point, but in the meantime feel free to put in PRs if you find the solution.

**Comment by englercj** [comment] 2018-05-28 17:19
Do you have a minimal example that reproduces this issue? The links don't seem valid anymore.

**Comment by wimrijnders** [comment] 2018-05-29 09:37
@englercj Well, this is a blast from the past; I'd completely forgotten about this and moved on, so it's not relevant for me any more. I wouldn't know how to reproduce it if I tried. I was hoping that indicating the position in the code would be sufficient.

I have no need for a fix here; if it all depends on me, you can close the issue. But perhaps your conscience will indulge you to have a go at fixing.

**Comment by englercj** [comment] 2018-05-29 14:49
> I was hoping that indicating the position in the code would be sufficient.

Unfortunately the link was to `master` rather than a specific revision. Since the code has changed I don't know what the block you linked to looked like :(

I'd like to fix the issue, but I don't have an example of how to cause the crash.

**Comment by wimrijnders** [comment] 2018-05-29 15:53
Oops my bad. TIL.

**Comment by wimrijnders** [comment] 2018-05-30 06:52
I browsed back in the history to find the relevant code.

[This is the latest revision containing it](https://github.com/englercj/tsd-jsdoc/blob/41e1c88d42691bcead752695bacd7a6f4ba78c5b/src/Emitter.ts#L2570).

By the looks of it, this is now a non-issue, since the code has changed significantly at that point.

HTH.

**Comment by englercj** [comment] 2018-05-30 15:34
Going to close this for now, and if it happens again we can fix it then.

**Closed by englercj** 2018-05-30 15:34 UTC
Labels: need more info

**Comment by wimrijnders** [comment] 2018-05-30 18:04
Totally agree! Good riddance to you, issue!
