### ISSUE TITLE
Custom type as any into @module

### ISSUE THREAD

**Issue by fabien0102** [englercj/tsd-jsdoc#24] opened 2017-03-31 08:51 UTC
Hello,

If I add `@module` on top of my file to generate a virtual namespace, typedef not following as expected.

Example:

```typescript
/**
 * @module GitGraph
 */
declare namespace GitGraph {
    /**
     * GitGraph Options
     * @typedef {object} GitGraphOptions
     * @property {string} [elementId = "gitGraph"] - Id of the canvas container
     * @property {Template|string|Object} [template] - Template of the graph
     * @property {string} [author = "Sergio Flores <saxo-guy@epic.com>"] - Default author for commits
     * @property {string} [mode = (null|"compact")]  - Display mode
     * @property {HTMLElement} [canvas] - DOM canvas (ex: document.getElementById("id"))
     * @property {string} [orientation = ("vertical-reverse"|"horizontal"|"horizontal-reverse")] - Graph orientation
     * @property {boolean} [reverseArrow = false] - Make arrows point to ancestors if true
     * @property {number} [initCommitOffsetX = 0] - Add custom offsetX to initial commit.
     * @property {number} [initCommitOffsetY = 0] - Add custom offsetY to initial commit.
     * @property {HTMLElement} [tooltipContainer = document.body] - HTML Element containing tooltips in compact mode.
     */
    type GitGraphOptions = {
        elementId: string;
        template: any | string | any;
        author: string;
        mode: string;
        canvas: any;
        orientation: string;
        reverseArrow: boolean;
        initCommitOffsetX: number;
        initCommitOffsetY: number;
        tooltipContainer: any;
    };

    /**
     * GitGraph
     * @constructor
     * @param {GitGraphOptions} options - GitGraph options
     * @this GitGraph
     */
    class GitGraph {
        constructor(options: any);
}
```

`options:any` should be `options.GitGraph.GitGraphOptions`

**Comment by englercj** [comment] 2017-03-31 15:31
Duplicate of #15

**Closed by englercj** 2017-03-31 15:31 UTC
