### ISSUE TITLE
Unable to resolve type name "Uint8Array".

### ISSUE THREAD

**Issue by ffflorian** [englercj/tsd-jsdoc#19] opened 2017-03-08 16:34 UTC
When I define a variable to be of type `Uint8Array`, I get the following error:
`[TSD-JSDoc] Unable to resolve type name "Uint8Array". No type found with that name, defaulting to "any".` 

-----------

Code example:
```js
/** @class */
class TestClass {
  /**
   * @param arr {Uint8Array}
   * @returns {Uint8Array}
   */
  testReturn(arr) {
    return arr;
  }
}
```

**Comment by englercj** [comment] 2017-03-08 17:45
Duplicate of #16

**Closed by englercj** 2017-03-08 17:45 UTC
